name: generate animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push to the master branch
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout the repository to get the latest code
      - name: Checkout repository
        uses: actions/checkout@v3  # Stable version

      # Debug step to confirm GitHub username
      - name: Debug GitHub Username
        run: echo "GitHub Username: shawaiz-khan"

      # Generates a snake game from the GitHub user's contribution graph
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: shawaiz-khan  # Ensure the username is correct

      # Debug step to confirm if the SVG file is generated
      - name: List files in dist directory
        run: |
          echo "Checking generated files in the dist directory..."
          ls -la dist

      # Push the generated SVG file to the 'output' branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
