name: Generate Snake Animation

on:
  schedule: # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository to the runner
      - name: Checkout
        uses: actions/checkout@v3

      # Generate snake.svg
      - name: Generate Snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      # Push the generated snake.svg to the output branch
      - name: Push Snake.svg to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}